module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  camp_utils: 0
  ckeditor: 0
  coffee: 0
  config: 0
  config_translation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  reroute_email: 0
  session_control: 0
  sparkpost: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  drupalcamp_base: 0
  drupalcamp_oslo_16: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: nb
