api_key: ''
sender: styret@drupalnorge.no
sender_name: 'Drupal Norge'
_core:
  default_config_hash: lwuTjJuABNwT-MOHY53_w6H37MVtiGb_6sZbhDow4lY
langcode: nb
debug: true
format: filtered_html
async: false
skip_cron: false
